#!/usr/bin/python

import os
import sys

fp = file("/etc/vnf_env.properties", "r")

eth = []

while True :
    line = fp.readline()
    if len(line) == 0 :
        break

    if line.find("hostname=") == 0 :
        line = line.replace("\n", "")
        hostname = line[line.find("=")+1:]
		hostname = hostname.strip()

    if line.find("interface_list=") == 0 :
        line = line.replace("\n", "")
        ethdevice = line[line.find("=")+1:].split(",")

fp.close()

sys.system("/bin/hostname %s" % hostname)

for eth in ethdevice :
    ip = ''
    gw = ''
    mask = ''

    fp = file(("/etc/vnf_%s_env.properties" % eth), "r")
    while True :
        line = fp.readline()

        if not line:
            break

        line = line.replace("\n", "")

        if "IP" in line :
            ip = line[line.find("=")+1:]
        elif "gateway" in line:
            gw = line[line.find("=")+1:]
        elif "subnetmask" in line:
            mask = line[line.find("=")+1:]

    if ip and gw and mask :
        cmd = "/sbin/ifconfig %s inet %s netmask %s up" % (eth, ip, mask)
        # print (cmd)
        os.system(cmd)

    fp.close()
